[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-isysroot",
    "-C", "link-arg=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk",
]

[env]
SDKROOT = "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
MACOSX_DEPLOYMENT_TARGET = "14.0"
